### ISSUE TITLE
index.ts in published package causes type errors

### ISSUE THREAD

**Issue by dantman** [bluelovers/env-bool#1]
When I try to typecheck my project with tsc I get a type error for env-bool.

```
node_modules/env-bool/index.ts:15:24 - error TS7006: Parameter 'val' implicitly has an 'any' type.

15 export function envVal(val)
                          ~~~

node_modules/env-bool/index.ts:84:25 - error TS7006: Parameter 'val' implicitly has an 'any' type.

84 export function envBool(val, mode2: boolean = true)
                           ~~~


Found 2 errors.
```

I've made a reproduction in stackblitz you can see with `npm test`.
https://stackblitz.com/edit/node-e5edng?devtoolsheight=33&file=index.ts

This appears to be because the source `index.ts` is published alongside the `index.js` and `index.d.ts`. When you import env-bool TypeScript seems to see the `index.ts` and try to typecheck it. If I locally delete the `index.ts` then tsc just reads the `index.d.ts` as normal and the package is fixed.

**Comment by bluelovers** [comment]
new version published

**Comment by dantman** [comment]
Thanks, the typecheck errors are gone now.
